# Required .env variables:
#
# POSTGRES_PASSWORD
# PGADMIN_HOST_PORT
# PGADMIN_DEFAULT_EMAIL
# PGADMIN_DEFAULT_PASSWORD

services:
  db:
    build:
      context: .
    restart: unless-stopped
    shm_size: 1G
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: pl_PL.UTF-8
      TZ: 'Europe/Warsaw'
      PGTZ: 'Europe/Warsaw'
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./backups:/backups

  pgadm4:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    user: root
    ports:
      - "${PGADMIN_HOST_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
      - ./backups:/backups
