version: '3.1'

# Required .env variables:
#
# POSTGRES_PASSWORD
# PGADMIN_HOST_PORT
# PGADMIN_DEFAULT_EMAIL
# PGADMIN_DEFAULT_PASSWORD

services:

  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: pl_PL.UTF-8
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadm4:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "${PGADMIN_HOST_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./servers.json:/pgadmin4/servers.json
